
server:
  port: 9091
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: "@project.name@"
    version: "@project.version@"
  jackson:
    date-format: dd-MM-yyyy
    locale: es_ES
    time-zone: Europe/Madrid
